spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./h2-persistent;DATABASE_TO_UPPER=false
    username: sa
    password:
  h2:
    console:
      enabled: true
doma:
  dialect: h2