spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./h2-persistent;DATABASE_TO_UPPER=false
    username: sa
    password:
  h2:
    console:
      enabled: true
doma:
  dialect: h2
  naming: SNAKE_LOWER_CASE
---
spring:
  profiles: unit
  datasource:
    url: jdbc:h2:mem:unit;DATABASE_TO_UPPER=false
flyway.schemas: PUBLIC
